In [90]:
import numpy as np
import scipy.linalg as la

In [91]:
n = 4

In [92]:
d = np.zeros((n, n), dtype = np.int64)
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [93]:
for i in range(n):
    d[i][0] = 1
d

array([[1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]], dtype=int64)

In [94]:
for i in range(1, n):
    for j in range(1, i+1):
        d[i][j] = - d[i][j-1] * ((i - j + 1) / j)
d

array([[ 1,  0,  0,  0],
       [ 1, -1,  0,  0],
       [ 1, -2,  1,  0],
       [ 1, -3,  3, -1]], dtype=int64)

In [99]:
k = d@d
k

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int64)

In [96]:
k == np.identity(4, dtype = np.int64)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [97]:
a = la.inv(d)
a

array([[ 1.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.],
       [ 1., -2.,  1.,  0.],
       [ 1., -3.,  3., -1.]])

In [98]:
a == d

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])