In [35]:
import numpy as np
import random

In [36]:
n = 3
m = 3

In [37]:
a = np.empty([n, m], dtype = int)
a

array([[   0,    1,    0],
       [   0, 1212,    0],
       [ 768,    0,    0]])

In [38]:
for i in range(n):
    for j in range(m):
        a[i][j] = np.random.randint(-20, 20)
a

array([[ -3,  19, -17],
       [  7, -18,   2],
       [ 19,   8,  17]])

In [39]:
a.flatten()

array([ -3,  19, -17,   7, -18,   2,  19,   8,  17])

In [40]:
s = np.sign(a)
s

array([[-1,  1, -1],
       [ 1, -1,  1],
       [ 1,  1,  1]])

In [41]:
b = np.empty([n, m], dtype = float)
for i in range(n):
    for j in range(m):
        b[i][j] = (abs(a[i][j]))**(1/2)
b

array([[1.73205081, 4.35889894, 4.12310563],
       [2.64575131, 4.24264069, 1.41421356],
       [4.35889894, 2.82842712, 4.12310563]])

In [42]:
c = np.trunc(b)
c

array([[1., 4., 4.],
       [2., 4., 1.],
       [4., 2., 4.]])

In [43]:
d = np.empty([n, m], dtype = float)
for i in range(n):
    for j in range(m):
        d[i][j] = (c[i][j])**2
d

array([[ 1., 16., 16.],
       [ 4., 16.,  1.],
       [16.,  4., 16.]])

In [44]:
d = d * s
d

array([[ -1.,  16., -16.],
       [  4., -16.,   1.],
       [ 16.,   4.,  16.]])

In [45]:
e = a == d
e

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [46]:
ee = np.where(e == True, 0, a)
ee

array([[ -3,  19, -17],
       [  7, -18,   2],
       [ 19,   8,  17]])

In [47]:
max_column = a.max(axis = 0)
min_max_column = min(max_column)
a, min_max_column, max_column

(array([[ -3,  19, -17],
        [  7, -18,   2],
        [ 19,   8,  17]]),
 17,
 array([19, 19, 17]))

In [48]:
min_row = a.min(axis = 1)
max_min_row = max(min_row)
max_min_row, min_row

(8, array([-17, -18,   8]))