In [1]:
import numpy as np

In [5]:
a = np.eye(5)

In [6]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Обход треугольника по горизонтали

In [16]:
def f (a):
    counter=0
    for i in range(a.shape[1]//2 + a.shape[1]%2):
        for y in range(i, a.shape[1]-i):
            a[i][y]=counter
            counter+=1

In [22]:
f(a)
a

array([[0., 1., 2., 3., 4.],
       [0., 5., 6., 7., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
b=np.eye(4)
f(b)

In [89]:
b=np.eye(6)

# Обход треугольника по вертикали

In [90]:
def f2(a):
    count=0
    for flag in range((a.shape[1]//2)//2):
        for i in range(flag, a.shape[1]//2 + a.shape[1]%2):
            a[i][i]=count
            count+=1
        
        for i in range(a.shape[1]//2,a.shape[1]-flag):
            a[a.shape[1] - i  -1][i]=count
            count+=1
            
        
        for y in range (a.shape[1]-flag -2, flag, -1):
            a[flag][y]=count
            count+=1

In [91]:
f2(b)

In [92]:
b


array([[0., 9., 8., 7., 6., 5.],
       [0., 1., 0., 0., 4., 0.],
       [0., 0., 2., 3., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])