In [123]:
import numpy as np
import random
n=5
m=6
a=np.zeros((n,m), dtype=np.int64)
print(a)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [124]:
for i in range(0, n):
    for j in range(0, m):
        a[i][j]=random.randint(-20, 20)
print(a)

[[-11   3  -5 -13  13 -12]
 [-14 -19  -3  -1   3   3]
 [ 18  -7  10  16  -2  -3]
 [-11  16  -7  16  13  14]
 [  2  -8   7 -16 -10  20]]


In [125]:
flat=a.flatten()
print(flat)

[-11   3  -5 -13  13 -12 -14 -19  -3  -1   3   3  18  -7  10  16  -2  -3
 -11  16  -7  16  13  14   2  -8   7 -16 -10  20]


In [126]:
s=np.sign(a)
b=np.sqrt(abs(a))
c=np.trunc(b)
d=c*c
d=s*d
a==d

array([[False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False,  True, False, False],
       [False,  True, False,  True, False, False],
       [False, False, False,  True, False, False]])

In [127]:
h = [print(i) for i in np.ndenumerate(a) if a[i[0]]!=d[i[0]]]

((0, 0), -11)
((0, 1), 3)
((0, 2), -5)
((0, 3), -13)
((0, 4), 13)
((0, 5), -12)
((1, 0), -14)
((1, 1), -19)
((1, 2), -3)
((1, 4), 3)
((1, 5), 3)
((2, 0), 18)
((2, 1), -7)
((2, 2), 10)
((2, 4), -2)
((2, 5), -3)
((3, 0), -11)
((3, 2), -7)
((3, 4), 13)
((3, 5), 14)
((4, 0), 2)
((4, 1), -8)
((4, 2), 7)
((4, 4), -10)
((4, 5), 20)


In [128]:
for i in np.ndenumerate(a): 
    if a[i[0]]!=d[i[0]]:
        a[i[0]]=random.randint(-20, 20)
print(a)

[[  3  12   5 -15   8   5]
 [  5   2 -15  -1  -4   0]
 [ 10  18   1  16 -10   4]
 [ 17  16  -5  16  19   4]
 [-17   7  16 -16 -20 -14]]


In [130]:
t=a.T
f=[max(t[i]) for i in range(m)]
f=min(f)
g=[min(a[i]) for i in range(n)]
g=max(g)
print(f==g)

[-15, -15, -10, -5, -20]
False
