In [76]:
import numpy as np
import scipy.linalg as la
n = 5
D = np.zeros((n,n), dtype = np.int64)
D[0] = 1
D = D.T

In [95]:
for i in range(1,n):
    for j in range(1,i+1):
        D[i][j] = -D[i][j-1]*(i-j+1)/j
print(D)

[[ 1  0  0  0  0]
 [ 1 -1  0  0  0]
 [ 1 -2  0  0  0]
 [ 1 -3  2  0  0]
 [ 1 -4  4 -1  0]]
1 1 1
2 1 2
2 2 1
3 1 3
3 2 2
3 3 1
4 1 4
4 2 3
4 3 2
4 4 1
[[ 1  0  0  0  0]
 [ 1 -1  0  0  0]
 [ 1 -2  1  0  0]
 [ 1 -3  3 -1  0]
 [ 1 -4  6 -4  1]]


In [96]:
D@D

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [98]:
D@D == np.identity(n) 

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [101]:
L = la.inv(D)
print(L)

[[ 1.  0.  0.  0.  0.]
 [ 1. -1.  0.  0.  0.]
 [ 1. -2.  1.  0.  0.]
 [ 1. -3.  3. -1.  0.]
 [ 1. -4.  6. -4.  1.]]


In [102]:
L == D

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])